[project]
name = "backend"
version = "0.1.0"
description = "server for mithril"
authors = [
    {name = "MericGit",email = "41242144+MericGit@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
